USE SNEAKERS;
SHOW TABLE;

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM SALES;
SELECT * FROM SALES_REP;
SELECT * FROM SUPPLIERS;

-- Objective 1: Analyzing Sales Performance
-- 1 . What is the total sales amount generated by each sales representative?
SELECT SR.FirstName, SUM(TotalAmount) AS TOTAL_SALES
FROM SALES AS S
JOIN SALES_REP as SR 
ON S.SalesRepID = SR.SalesRepID
GROUP BY SR.FirstName 
ORDER BY TOTAL_SALES DESC ;


-- 2. How many products have been sold in each store location?
SELECT S.STORELOCATION, COUNT(S.ProductID) AS PSALES
FROM SALES AS S
JOIN PRODUCTS AS P 
ON S.ProductID = P.ProductID
GROUP BY S.STORELOCATION;



-- 3. Which product category has the highest total sales amount?
SELECT P.CATEGORY, SUM(S.TotalAmount) AS t_SALES
FROM PRODUCTS AS P
Join SALES as S
ON P.ProductID = S.ProductID
group by P.CATEGORY
ORDER BY t_SALES DESC LIMIT 1;


-- 4. What is the average quantity of products sold per sale?
SELECT AVG(QUANTITY) AS AVG_QUAN
FROM SALES;



-- 5. Which customer has made the highest number of purchases?
SELECT C.FIRSTNAME 
FROM CUSTOMERS AS C
JOIN SALES AS S
WHERE C.CUSTOMERID = S.CUSTOMERID
ORDER BY S.TOTALAMOUNT DESC LIMIT 1;

-- 6. What is the distribution of total sales amounts across different months?
SELECT extract(MONTH FROM DATE) AS D_month , SUM(TotalAmount) as T_Sales
FROM SALES
GROUP BY D_month
ORDER BY D_month;


-- 7. How does the sales performance of different regions compare?
SELECT SUM(QUANTITY) AS s_PER , STORELOCATION 
FROM Sales
GROUP BY STORELOCATION
ORDER BY s_PER DESC;



-- 8. What is the total sales amount generated for each product?
SELECT SUM(S.TOTALAMOUNT) AS TOTAL_SALES, P.PRODUCTNAME
FROM SALES as S
JOIN PRODUCTS AS P 
ON S.PRODUCTID = P.PRODUCTID
GROUP BY PRODUCTNAME
ORDER BY TOTAL_SALES DESC;


-- 9. What is the average sales amount per transaction?
SELECT AVG(TOTALAMOUNT) as avg_sale_per_transaction
FROM SALES;


-- 10. How many sales transactions were made by each sales representative?
SELECT SR.FirstName,COUNT(S.SaleID) AS sales_transcation
FROM sales AS S 
JOIN sales_rep AS SR
ON S.SalesRepID = SR.SalesRepID
GROUP BY FirstName;

























































































